### ISSUE TITLE
Missing normalize file

### ISSUE THREAD

**Issue by durgoth** [dsandstrom/task_roller#9]
couldn't find file 'normalize.css/normalize' with type 'text/css'
Checked in these paths: 
  /home/sjones/development/task_roller/app/assets/config
  /home/sjones/development/task_roller/app/assets/fonts
  /home/sjones/development/task_roller/app/assets/images
  /home/sjones/development/task_roller/app/assets/stylesheets
  /home/sjones/development/task_roller/vendor/assets/stylesheets
  /home/sjones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/coffee-rails-5.0.0/lib/assets/javascripts
  /home/sjones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activestorage-6.0.3.3/app/assets/javascripts
  /home/sjones/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionview-6.0.3.3/lib/assets/compiled
  /home/sjones/development/task_roller/node_modules

<html>
  <head>
    <title>TaskRoller</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all',
                            'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'flash_messages', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'forms', 'data-turbolinks-track': 'reload' %>

**Comment by dsandstrom** [comment]
You seem to be missing some npm/yarn steps, let me look into it.

**Comment by dsandstrom** [comment]
Adding this to the readme:

---

#### Install Frontend Dependencies
I use [Node Version Manager](https://github.com/nvm-sh/nvm) to maintain a more
consistent node version.  The version number is stored in *~./.nvmrc*. Please
use that version of NodeJS or use nvm to install it.

```sh
# using nvm
# cd into project directory
nvm install
nvm use
```

Install frontend packages with yarn
```sh
yarn install
```
---

Please give that a shot

**Comment by dsandstrom** [comment]
I need to add something for installing yarn

https://classic.yarnpkg.com/en/docs/install
